-- ==============================================
-- ENUM TYPES FOR POSTGRESQL
-- ==============================================

-- Users
CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION');
CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY');
CREATE TYPE token_type AS ENUM ('ACCESS', 'REFRESH', 'RESET_PASSWORD', 'EMAIL_VERIFICATION');
CREATE TYPE user_role AS ENUM ('ADMIN', 'RECRUITER', 'CANDIDATE');

-- Jobs
CREATE TYPE job_status AS ENUM ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'SUSPENDED', 'CLOSED');
CREATE TYPE job_level_type AS ENUM ('INTERN', 'JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', 'MANAGER');
CREATE TYPE working_model_type AS ENUM ('REMOTE', 'ONSITE', 'HYBRID');
CREATE TYPE currency AS ENUM ('VND', 'USD');

-- Applications
CREATE TYPE application_status AS ENUM ('APPLIED', 'VIEWED', 'SHORTLISTED', 'AUTO_REJECTED', 'NOT_SUITABLE');

-- Candidates
CREATE TYPE candidate_show_as AS ENUM ('PROFILE', 'RESUME');

-- Criteria
CREATE TYPE criteria_type AS ENUM ('HARD_SKILLS', 'SOFT_SKILLS', 'EXPERIENCE', 'EDUCATION', 'JOB_TITLE', 'JOB_LEVEL');

-- Company
CREATE TYPE company_status AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED');
CREATE TYPE company_type AS ENUM ('PRODUCT','OUTSOURCING','CONSULTING','SERVICE','SOLUTION','SYSTEM_INTEGRATOR','AGENCY');
CREATE TYPE company_industry AS ENUM ('INFORMATION_TECHNOLOGY','FINTECH','ECOMMERCE','HEALTHCARE','EDUCATION','LOGISTICS','MANUFACTURING','REAL_ESTATE','GAMING','TELECOMMUNICATION','ARTIFICIAL_INTELLIGENCE','CYBER_SECURITY','BLOCKCHAIN','IOT');

-- Resume
CREATE TYPE resume_status AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
CREATE TYPE resume_language AS ENUM ('VI', 'EN');
CREATE TYPE parse_status AS ENUM ('WAITING', 'PARTIAL', 'FINISH', 'FAIL');
CREATE TYPE resume_type AS ENUM ('ORIGINAL', 'TEMPLATE', 'PROFILE');
CREATE TYPE degree_type AS ENUM ('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE', 'CERTIFICATE');
CREATE TYPE project_type AS ENUM ('PERSONAL', 'ACADEMIC', 'PROFESSIONAL', 'OPEN_SOURCE', 'FREELANCE');
CREATE TYPE employment_type AS ENUM (
  'FULL_TIME',
  'PART_TIME',
  'SELF_EMPLOYED',
  'FREELANCE',
  'CONTRACT',
  'INTERNSHIP',
  'APPRENTICESHIP',
  'SEASONAL'
);

-- Evaluation
CREATE TYPE gap_type AS ENUM ('HARD_SKILL', 'SOFT_SKILL', 'EXPERIENCE', 'EDUCATION', 'CERTIFICATION');
CREATE TYPE impact_type AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');
CREATE TYPE match_level_type AS ENUM ('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'NOT_MATCHED');
CREATE TYPE evaluation_status_type AS ENUM ('WAITING', 'PARTIAL', 'FINISH', 'FAIL');
CREATE TYPE skill_category_type AS ENUM ('PROGRAMMING_LANGUAGE', 'FRAMEWORK', 'TOOL', 'DATABASE', 'OTHER');
CREATE TYPE skill_level_type AS ENUM ('JUNIOR', 'MID', 'SENIOR', 'EXPERT');
CREATE TYPE relevance_type AS ENUM ('HIGH', 'MEDIUM', 'LOW');
CREATE TYPE transferability_type AS ENUM ('HIGH', 'MEDIUM', 'LOW');
CREATE TYPE experience_gravity_type AS ENUM ('HIGH', 'MEDIUM', 'LOW');

-- Plan & Subscription
CREATE TYPE plan_target_type AS ENUM ('COMPANY', 'CANDIDATE');
CREATE TYPE plan_type AS ENUM ('ADDONS_FEATURE', 'ADDONS_QUOTA', 'MAIN');
CREATE TYPE plan_duration_unit AS ENUM ('MONTH', 'YEAR');
CREATE TYPE feature_usage_type AS ENUM ('BOOLEAN', 'EVENT', 'STATE');
CREATE TYPE usage_limit_unit AS ENUM ('TOTAL', 'PER_MONTH');
CREATE TYPE subscription_status AS ENUM ('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING_PAYMENT');
CREATE TYPE payment_method_type AS ENUM ('CREDIT_CARD', 'VNPAY', 'SEPAY', 'MOMO', 'BANK_TRANSFER');
CREATE TYPE payment_status_type AS ENUM ('PENDING', 'SUCCESS', 'FAILED');

-- Notifications
CREATE TYPE notification_type AS ENUM ('APPLICATION_STATUS', 'REJECTION', 'COMPANY_REGISTRATION', 'FLAGGED_JOB', 'PAYMENT_FAILURE', 'AI_DOWNTIME', 'SYSTEM');

-- Export
CREATE TYPE export_type AS ENUM ('XLSX', 'CSV');

-- ==============================================
-- TABLE DEFINITIONS
-- ==============================================

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  status user_status,
  full_name varchar(255),
  avatar varchar(500),
  last_login_at TIMESTAMP,
  date_of_birth TIMESTAMP,
  gender gender_type,
  role user_role
);

CREATE TABLE user_tokens (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  token varchar(500) UNIQUE NOT NULL,
  token_type token_type NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  revoked boolean DEFAULT false,
  revoked_at TIMESTAMP,
  ip_address varchar(45),
  user_agent varchar(500)
);

CREATE TABLE candidates (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int UNIQUE NOT NULL,
  job_title varchar(255),
  linkedin_url varchar(500),
  github_url varchar(500),
  website_url varchar(500),
  address varchar(500),
  expected_salary_min decimal(15,2),
  expected_salary_max decimal(15,2),
  availability_date date,
  is_profile_public boolean DEFAULT true,
  show_as candidate_show_as DEFAULT 'RESUME',
  profile_completeness int DEFAULT 0
);

CREATE TABLE recruiters (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int UNIQUE NOT NULL,
  company_id int NOT NULL,
  is_verified boolean DEFAULT false,
  is_root_recruiter boolean DEFAULT false,
  verified_at TIMESTAMP
);

CREATE TABLE jobs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  about text,
  responsibilities text,
  requirement text,
  is_violated boolean,
  upload_time TIMESTAMP,
  exp_date TIMESTAMP,
  salary_start decimal(15,2),
  salary_end decimal(15,2),
  currency varchar(3) DEFAULT 'VND',
  experience_time int,
  enable_ai_scoring boolean,
  status job_status,
  job_level job_level_type,
  working_model working_model_type,
  quantity int,
  auto_reject_threshold DOUBLE PRECISION,
  root_id int,
  company_id int,
  expertise_id int
);

CREATE TABLE applications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status application_status,
  attempt int,
  full_name varchar,
  phone varchar,
  email varchar,
  applied_at TIMESTAMP,
  candidate_id int,
  resume_id int,
  job_id int
);

CREATE TABLE scoring_criterias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  context text,
  weight DOUBLE PRECISION,
  job_id int,
  criteria_id int
);

CREATE TABLE criterias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  criteria_type criteria_type,
  default_weight DOUBLE PRECISION
);

CREATE TABLE job_marks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int,
  job_id int
);

CREATE TABLE job_expertise_groups (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE benefits (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE job_benefits (
  job_id int,
  benefit_id int,
  PRIMARY KEY (job_id, benefit_id)
);

CREATE TABLE job_locations (
  company_location_id int,
  job_id int,
  PRIMARY KEY (company_location_id, job_id)
);

CREATE TABLE job_questions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  is_required bool,
  description text,
  job_id int
);

CREATE TABLE job_answers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  answer text,
  application_id int,
  job_question_id int
);

CREATE TABLE domains (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE job_domains (
  job_id int,
  domain_id int,
  PRIMARY KEY (job_id, domain_id)
);

CREATE TABLE job_expertises (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text,
  expertise_group_id int
);

CREATE TABLE job_skills (
  skill_id int,
  job_id int
);

CREATE TABLE company_images (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url varchar,
  description varchar
);

CREATE TABLE companies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  country varchar,
  company_industry varchar,
  size varchar,
  description text,
  link varchar,
  follower_number int,
  status company_status,
  company_type varchar,
  logo varchar,
  tax_identification_number varchar,
  email varchar,
  phone varchar,
  sign_commitment boolean,
  erc varchar
);

CREATE TABLE company_blocked_candidates (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id int,
  block_date TIMESTAMP,
  reason varchar
);

CREATE TABLE company_follows (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int,
  candidate_id int
);

CREATE TABLE company_locations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int NOT NULL,
  name varchar,
  address varchar,
  district varchar,
  city varchar,
  country varchar,
  description varchar,
  longitude decimal(10, 7),
  latitude decimal(10, 7),
  google_map_link varchar(500)
);

CREATE TABLE resumes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_name varchar,
  file_name varchar,
  resume_url varchar(500),
  raw_text text,
  address_in_resume varchar,
  phone_in_resume varchar,
  email_in_resume varchar,
  github_link varchar,
  linkedin_link varchar,
  portfolio_link varchar,
  full_name varchar,
  avatar varchar,
  type resume_type DEFAULT 'ORIGINAL',
  root_resume_id int,
  status resume_status,
  parse_status parse_status DEFAULT 'WAITING',
  language resume_language,
  is_default boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  candidate_id int
);

CREATE TABLE skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar,
  category_id int
);

CREATE TABLE skill_categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE resume_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  years_of_experience int,
  skill_group_id int NOT NULL,
  skill_id int NOT NULL
);

CREATE TABLE resume_skill_groups (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  order_index int NOT NULL,
  resume_id int NOT NULL
);

CREATE TABLE resume_educations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution varchar,
  degree degree_type,
  major_field varchar,
  gpa DOUBLE PRECISION,
  start_date date,
  end_date date,
  is_current bool,
  order_index int NOT NULL,
  resume_id int
);

CREATE TABLE resume_experiences (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company varchar,
  start_date date,
  end_date date,
  is_current bool,
  working_model working_model_type,
  employment_type employment_type,
  order_index int NOT NULL,
  resume_id int
);

CREATE TABLE resume_projects (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar,
  team_size int,
  position varchar,
  description text,
  project_type project_type,
  start_date date,
  end_date date,
  is_current bool,
  project_url varchar,
  order_index int NOT NULL,
  resume_id int
);

CREATE TABLE resume_certifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  issuer varchar,
  credential_url varchar,
  image varchar,
  description text,
  resume_id int
);

CREATE TABLE resume_experience_details (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  title varchar,
  start_date date,
  end_date date,
  is_current bool,
  order_index int NOT NULL,
  experience_id int
);

CREATE TABLE experience_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  detail_id int,
  skill_id int
);

CREATE TABLE project_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  project_id int,
  skill_id int
);

CREATE TABLE evaluation_gaps (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gap_type gap_type,
  item_name varchar,
  description text,
  impact impact_type,
  impact_score float,
  suggestion text,
  evaluation_id int
);

CREATE TABLE evaluation_weaknesses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weakness_text text,
  suggestion text,
  start_index int,
  end_index int,
  context varchar,
  criterion_type criteria_type,
  severity smallint,
  evaluation_id int
);

CREATE TABLE resume_evaluations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_overall_score float,
  recruiter_overall_score float,
  match_level match_level_type,
  summary text,
  strengths text,
  weakness text,
  is_true_level bool,
  has_related_experience bool,
  is_specific_jd bool,
  evaluation_status evaluation_status_type,
  processing_time_second float,
  ai_model_version varchar,
  resume_id int,
  job_id int
);

CREATE TABLE evaluation_criteria_scores (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_criteria_id int,
  max_score float DEFAULT 100,
  ai_score float,
  manual_score float,
  weighted_score float,
  ai_explanation text,
  manual_explanation text,
  evaluation_id int
);

CREATE TABLE evaluation_hard_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name varchar,
  evidence text,
  skill_category skill_category_type,
  required_level skill_level_type,
  candidate_level skill_level_type,
  match_score float,
  years_of_experience float,
  is_critical bool,
  is_matched bool,
  is_missing bool,
  is_extra bool,
  relevance relevance_type,
  evaluation_criteria_score_id int
);

CREATE TABLE evaluation_soft_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name varchar,
  evidence text,
  is_required boolean,
  is_found boolean,
  evaluation_criteria_score_id int
);

CREATE TABLE evaluation_experience_details (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name varchar,
  position varchar,
  duration_months int,
  key_achievements text,
  technologies_used text,
  is_relevant boolean,
  transferability_to_role transferability_type,
  experience_gravity experience_gravity_type,
  evaluation_criteria_score_id int
);

CREATE TABLE plans (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  description text,
  plan_details text,
  plan_target plan_target_type NOT NULL,
  plan_type plan_type NOT NULL,
  currency varchar(3) NOT NULL DEFAULT 'VND',
  is_active boolean NOT NULL DEFAULT true,
  is_popular boolean NOT NULL DEFAULT false
);

CREATE TABLE plan_prices (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id int NOT NULL,
  original_price decimal(15,2) NOT NULL DEFAULT 0,
  sale_price decimal(15,2) NOT NULL DEFAULT 0,
  currency varchar(3) NOT NULL DEFAULT 'VND',
  duration int NOT NULL,
  unit plan_duration_unit NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE features (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  description text,
  usage_type feature_usage_type,
  feature_key varchar(100) UNIQUE NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE usage_limits (
  plan_id int NOT NULL,
  feature_id int NOT NULL,
  max_quota int NOT NULL,
  limit_unit usage_limit_unit NOT NULL,
  PRIMARY KEY (plan_id, feature_id)
);

CREATE TABLE subscriptions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int,
  candidate_id int,
  plan_id int NOT NULL,
  price decimal(15,2) NOT NULL DEFAULT 0,
  status subscription_status NOT NULL DEFAULT 'PENDING_PAYMENT',
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  purchased_at TIMESTAMP DEFAULT now(),
  renewed_at TIMESTAMP,
  CONSTRAINT subscriptions_company_candidate_xor CHECK (
    (company_id IS NOT NULL AND candidate_id IS NULL)
    OR (company_id IS NULL AND candidate_id IS NOT NULL)
  )
);

CREATE TABLE usage_events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id int NOT NULL,
  feature_id int NOT NULL,
  amount int NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE payment_histories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id int NOT NULL,
  amount decimal(15,2) NOT NULL,
  currency varchar(3) NOT NULL DEFAULT 'VND',
  payment_method payment_method_type NOT NULL,
  payment_status payment_status_type NOT NULL DEFAULT 'PENDING',
  transaction_code varchar(255),
  paid_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE notifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  notification_type notification_type NOT NULL,
  title varchar(255) NOT NULL,
  message text NOT NULL,
  related_entity_type varchar(50),
  related_entity_id int,
  is_read boolean NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE notification_settings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  notification_type notification_type NOT NULL,
  email_enabled boolean NOT NULL DEFAULT true,
  in_app_enabled boolean NOT NULL DEFAULT true
);

CREATE TABLE faqs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category varchar(100) NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  is_published boolean NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE export_records (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exported_by int NOT NULL,
  job_id int NOT NULL,
  export_type export_type NOT NULL,
  candidate_count int NOT NULL DEFAULT 0,
  file_url varchar(500),
  created_at TIMESTAMP DEFAULT now()
);

-- ==============================================
-- TRIGGERS
-- ==============================================

CREATE OR REPLACE FUNCTION normalize_skill_category_name_trigger()
RETURNS trigger AS
$$
DECLARE
    normalized text;
BEGIN
    IF NEW.name IS NULL THEN
        RETURN NEW;
    END IF;

    normalized := LOWER(REGEXP_REPLACE(TRIM(NEW.name), '\s+', ' ', 'g'));

    NEW.name := CASE
        WHEN normalized IN ('programming languages', 'programming language') THEN 'Programming Language'
        WHEN normalized IN ('frameworks', 'framework') THEN 'Framework'
        WHEN normalized IN ('tools', 'tool', 'tools & technologies') THEN 'Tool'
        WHEN normalized IN ('databases', 'database') THEN 'Database'
        WHEN normalized IN ('frontends', 'frontend') THEN 'Frontend'
        WHEN normalized IN ('backends', 'backend') THEN 'Backend'
        WHEN normalized IN ('soft skills', 'soft skill') THEN 'Soft Skill'
        WHEN normalized IN ('methodologies', 'methodology') THEN 'Methodology'
        WHEN normalized IN ('clouds', 'cloud') THEN 'Cloud'
        ELSE REGEXP_REPLACE(TRIM(NEW.name), '\s+', ' ', 'g')
    END;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_normalize_skill_category_name ON skill_categories;
CREATE TRIGGER trg_normalize_skill_category_name
BEFORE INSERT OR UPDATE ON skill_categories
FOR EACH ROW
EXECUTE FUNCTION normalize_skill_category_name_trigger();

-- ==============================================
-- INDEXES
-- ==============================================

CREATE UNIQUE INDEX ON notification_settings (user_id, notification_type);
CREATE UNIQUE INDEX uq_skill_categories_name_normalized ON skill_categories ((LOWER(REGEXP_REPLACE(TRIM(name), '\s+', ' ', 'g'))));
CREATE UNIQUE INDEX uq_skills_name_normalized ON skills ((LOWER(REGEXP_REPLACE(TRIM(name), '\s+', ' ', 'g'))));
CREATE UNIQUE INDEX uq_resume_skill_groups_name_per_resume ON resume_skill_groups (resume_id, (LOWER(REGEXP_REPLACE(TRIM(name), '\s+', ' ', 'g'))));
CREATE UNIQUE INDEX uq_resumes_one_profile_per_candidate ON resumes (candidate_id) WHERE type = 'PROFILE';

-- ==============================================
-- FOREIGN KEYS
-- ==============================================
ALTER TABLE candidates ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE recruiters ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE recruiters ADD FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;

ALTER TABLE user_tokens ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE job_domains ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_domains ADD FOREIGN KEY (domain_id) REFERENCES domains (id);

ALTER TABLE job_benefits ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_benefits ADD FOREIGN KEY (benefit_id) REFERENCES benefits (id);

ALTER TABLE job_expertises ADD FOREIGN KEY (expertise_group_id) REFERENCES job_expertise_groups (id);

ALTER TABLE job_answers ADD FOREIGN KEY (job_question_id) REFERENCES job_questions (id);

ALTER TABLE job_marks ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_marks ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE applications ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE applications ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE job_answers ADD FOREIGN KEY (application_id) REFERENCES applications (id);

ALTER TABLE job_questions ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE scoring_criterias ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE jobs ADD FOREIGN KEY (root_id) REFERENCES jobs (id);

ALTER TABLE scoring_criterias ADD FOREIGN KEY (criteria_id) REFERENCES criterias (id);

ALTER TABLE job_skills ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE job_locations ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_locations ADD FOREIGN KEY (company_location_id) REFERENCES company_locations (id);

ALTER TABLE resumes ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE resumes ADD FOREIGN KEY (root_resume_id) REFERENCES resumes (id);

ALTER TABLE resume_skill_groups ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE resume_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_skills ADD FOREIGN KEY (skill_group_id) REFERENCES resume_skill_groups (id);

ALTER TABLE resume_educations ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE skills ADD FOREIGN KEY (category_id) REFERENCES skill_categories (id);

ALTER TABLE resume_projects ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE project_skills ADD FOREIGN KEY (project_id) REFERENCES resume_projects (id);

ALTER TABLE project_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_experiences ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE resume_experience_details ADD FOREIGN KEY (experience_id) REFERENCES resume_experiences (id);

ALTER TABLE experience_skills ADD FOREIGN KEY (detail_id) REFERENCES resume_experience_details (id);

ALTER TABLE experience_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_certifications ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE evaluation_weaknesses ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE resume_evaluations ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE evaluation_criteria_scores ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE plan_prices ADD FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE CASCADE;

ALTER TABLE usage_limits ADD FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE CASCADE;

ALTER TABLE usage_limits ADD FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE;

ALTER TABLE subscriptions ADD FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;

ALTER TABLE subscriptions ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id) ON DELETE CASCADE;

ALTER TABLE subscriptions ADD FOREIGN KEY (plan_id) REFERENCES plans (id);

ALTER TABLE usage_events ADD FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE;

ALTER TABLE usage_events ADD FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE;

ALTER TABLE payment_histories ADD FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE;

ALTER TABLE applications ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE notifications ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notification_settings ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE export_records ADD FOREIGN KEY (exported_by) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE export_records ADD FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE;

ALTER TABLE company_follows ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE company_blocked_candidates ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE company_images ADD FOREIGN KEY (id) REFERENCES companies (id);

ALTER TABLE company_locations ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE jobs ADD FOREIGN KEY (expertise_id) REFERENCES job_expertises (id);

ALTER TABLE jobs ADD FOREIGN KEY (company_id) REFERENCES companies (id);


ALTER TABLE evaluation_hard_skills ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_soft_skills ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_experience_details ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_gaps ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE evaluation_criteria_scores ADD FOREIGN KEY (scoring_criteria_id) REFERENCES scoring_criterias (id);
