-- ==============================================
-- ENUM TYPES FOR POSTGRESQL
-- ==============================================

-- Users
CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended', 'pending_verification');
CREATE TYPE gender_type AS ENUM ('male', 'female', 'other', 'prefer_not_to_say');
CREATE TYPE token_type AS ENUM ('access', 'refresh', 'reset_password', 'email_verification');

-- Jobs
CREATE TYPE job_status AS ENUM ('draft', 'pending_review', 'approved', 'suspended', 'closed');
CREATE TYPE job_level_type AS ENUM ('intern', 'junior', 'middle', 'senior', 'lead', 'manager');
CREATE TYPE working_model_type AS ENUM ('remote', 'onsite', 'hybrid');

-- Applications
CREATE TYPE application_status AS ENUM ('pending', 'reviewing', 'shortlisted', 'interview', 'offer', 'hired', 'rejected', 'withdrawn');

-- Candidates
CREATE TYPE job_search_status AS ENUM ('actively_looking', 'open_to_offers', 'not_looking');

-- Criteria
CREATE TYPE criteria_type AS ENUM ('hard_skills', 'soft_skills', 'experience', 'education', 'job_title', 'job_level');

-- Company
CREATE TYPE company_status AS ENUM ('active', 'inactive', 'pending_verification', 'suspended');

-- Resume
CREATE TYPE resume_status AS ENUM ('draft', 'active', 'archived');
CREATE TYPE resume_language AS ENUM ('vi', 'en');
CREATE TYPE degree_type AS ENUM ('high_school', 'associate', 'bachelor', 'master', 'doctorate', 'certificate');
CREATE TYPE project_type AS ENUM ('personal', 'academic', 'professional', 'open_source', 'freelance');

-- Evaluation
CREATE TYPE gap_type AS ENUM ('hard_skill', 'soft_skill', 'experience', 'education', 'certification');
CREATE TYPE impact_type AS ENUM ('critical', 'high', 'medium', 'low');
CREATE TYPE match_level_type AS ENUM ('excellent', 'good', 'fair', 'poor', 'not_matched');
CREATE TYPE evaluation_status_type AS ENUM ('waiting', 'partial', 'finish', 'fail');
CREATE TYPE skill_category_type AS ENUM ('programming_language', 'framework', 'tool', 'database', 'other');
CREATE TYPE skill_level_type AS ENUM ('junior', 'mid', 'senior', 'expert');
CREATE TYPE relevance_type AS ENUM ('high', 'medium', 'low');
CREATE TYPE transferability_type AS ENUM ('high', 'medium', 'low');
CREATE TYPE experience_gravity_type AS ENUM ('high', 'medium', 'low');

-- Packages
CREATE TYPE package_target_type AS ENUM ('candidate', 'company');
CREATE TYPE package_type AS ENUM ('credit', 'feature');
CREATE TYPE billing_cycle_type AS ENUM ('monthly', 'yearly', 'one_time');
CREATE TYPE subscription_status AS ENUM ('active', 'expired', 'cancelled', 'pending_payment');
CREATE TYPE credit_type AS ENUM ('earned', 'consumed', 'expired', 'bonus');
CREATE TYPE reference_type AS ENUM ('ai_suggestion', 'matching_score', 'cv_score', 'talent_unlock', 'cycle_reset', 'trial');
CREATE TYPE payment_method_type AS ENUM ('credit_card', 'vnpay', 'sepay', 'momo', 'bank_transfer');
CREATE TYPE payment_status_type AS ENUM ('pending', 'success', 'failed');

-- Notifications
CREATE TYPE notification_type AS ENUM ('application_status', 'rejection', 'company_registration', 'flagged_job', 'payment_failure', 'ai_downtime', 'system');

-- Export
CREATE TYPE export_type AS ENUM ('xlsx', 'csv');

-- ==============================================
-- TABLE DEFINITIONS
-- ==============================================

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  status user_status,
  full_name varchar(255),
  avatar varchar(500),
  last_login_at TIMESTAMP,
  date_of_birth date,
  gender gender_type
);

CREATE TABLE user_tokens (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  token varchar(500) UNIQUE NOT NULL,
  token_type token_type NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  revoked boolean DEFAULT false,
  revoked_at TIMESTAMP,
  ip_address varchar(45),
  user_agent varchar(500)
);

CREATE TABLE users_roles (
  user_id int,
  role_id int,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(10)
);

CREATE TABLE candidates (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int UNIQUE NOT NULL,
  job_title varchar(255),
  linkedin_url varchar(500),
  github_url varchar(500),
  website_url varchar(500),
  expected_salary_min decimal(15,2),
  expected_salary_max decimal(15,2),
  job_search_status job_search_status DEFAULT 'open_to_offers',
  availability_date date,
  is_profile_public boolean DEFAULT true,
  profile_completeness int DEFAULT 0
);

CREATE TABLE recruiters (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int UNIQUE NOT NULL,
  company_id int NOT NULL,
  is_verified boolean DEFAULT false,
  is_root_candidate boolean DEFAULT false,
  verified_at TIMESTAMP
);

CREATE TABLE jobs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  about text,
  responsibilities text,
  requirement text,
  is_violated boolean,
  upload_time TIMESTAMP,
  exp_date TIMESTAMP,
  salary varchar,
  experience_time varchar,
  status job_status,
  job_level job_level_type,
  working_model working_model_type,
  quantity int,
  auto_reject_threshold DOUBLE PRECISION,
  root_id int,
  company_id int
);

CREATE TABLE applications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status application_status,
  attempt int,
  full_name varchar,
  phone varchar,
  email varchar,
  applied_at TIMESTAMP,
  candidate_id int,
  resume_id int,
  job_id int
);

CREATE TABLE scoring_criterias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  context text,
  weight DOUBLE PRECISION,
  job_id int,
  criteria_id int
);

CREATE TABLE criterias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  criteria_type criteria_type,
  default_weight DOUBLE PRECISION
);

CREATE TABLE job_marks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int,
  job_id int
);

CREATE TABLE job_expertise_groups (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE job_benefits (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE job_locations (
  company_location_id int,
  job_id int
);

CREATE TABLE job_questions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  is_required bool,
  description text,
  job_id int
);

CREATE TABLE job_answers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  answer text,
  application_id int,
  job_question_id int
);

CREATE TABLE job_domains (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE job_expertises (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE job_skills (
  skill_id int,
  job_id int
);

CREATE TABLE company_images (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url varchar,
  description varchar
);

CREATE TABLE companies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  country varchar,
  company_industry varchar,
  size varchar,
  description text,
  link varchar,
  follower_number int,
  status company_status,
  company_type varchar,
  logo varchar,
  tax_identification_number varchar,
  email varchar,
  phone varchar,
  sign_commitment boolean,
  erc varchar
);

CREATE TABLE company_blocked_candidates (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id int,
  block_date TIMESTAMP,
  reason varchar
);

CREATE TABLE company_follows (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int,
  candidate_id int
);

CREATE TABLE company_locations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int NOT NULL,
  name varchar,
  address varchar,
  district varchar,
  city varchar,
  country varchar,
  description varchar
);

CREATE TABLE resumes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name varchar,
  original_file varchar,
  raw_text text,
  address_in_resume varchar,
  phone_in_resume varchar,
  email_in_resume varchar,
  github_link varchar,
  linkedin_link varchar,
  portfolio_link varchar,
  full_name varchar,
  avatar varchar,
  status resume_status,
  language resume_language,
  candidate_id int
);

CREATE TABLE skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar,
  category_id int
);

CREATE TABLE skill_categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE resume_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_skill_section TEXT,
  skill_id int,
  resume_id int
);

CREATE TABLE resume_educations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution varchar,
  degree degree_type,
  major_field varchar,
  gpa DOUBLE PRECISION,
  start_date date,
  end_date date,
  is_current bool,
  resume_id int
);

CREATE TABLE resume_experiences (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company varchar,
  start_date date,
  end_date date,
  is_current bool,
  resume_id int
);

CREATE TABLE resume_projects (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar,
  team_size int,
  position varchar,
  description text,
  project_type project_type,
  start_date date,
  end_date date,
  is_current bool,
  project_url varchar,
  resume_id int
);

CREATE TABLE resume_certifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  issuer varchar,
  credential_url varchar,
  image varchar,
  description text,
  resume_id int
);

CREATE TABLE resume_experience_details (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  title varchar,
  position varchar,
  start_date date,
  end_date date,
  is_current bool,
  experience_id int
);

CREATE TABLE experience_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  detail_id int,
  skill_id int
);

CREATE TABLE project_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  project_id int,
  skill_id int
);

CREATE TABLE evaluation_gaps (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gap_type gap_type,
  item_name varchar,
  description text,
  impact impact_type,
  impact_score float,
  suggestion text,
  evaluation_id int
);

CREATE TABLE evaluation_weaknesses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weakness_text text,
  suggestion text,
  start_index int,
  end_index int,
  context varchar,
  criterion_type criteria_type,
  severity smallint,
  evaluation_id int
);

CREATE TABLE resume_evaluations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_overall_score float,
  recruiter_overall_score float,
  match_level match_level_type,
  summary text,
  strengths text,
  weakness text,
  is_true_level bool,
  has_related_experience bool,
  is_specific_jd bool,
  evaluation_status evaluation_status_type,
  processing_time_second float,
  ai_model_version varchar,
  resume_id int,
  job_id int
);

CREATE TABLE evaluation_criteria_scores (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_criteria_id int,
  max_score float DEFAULT 100,
  ai_score float,
  manual_score float,
  weighted_score float,
  ai_explanation text,
  manual_explanation text,
  evaluation_id int
);

CREATE TABLE evaluation_hard_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name varchar,
  evidence text,
  skill_category skill_category_type,
  required_level skill_level_type,
  candidate_level skill_level_type,
  match_score float,
  years_of_experience float,
  is_critical bool,
  is_matched bool,
  is_missing bool,
  is_extra bool,
  relevance relevance_type,
  evaluation_criteria_score_id int
);

CREATE TABLE evaluation_soft_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name varchar,
  evidence text,
  is_required boolean,
  is_found boolean,
  evaluation_criteria_score_id int
);

CREATE TABLE evaluation_experience_details (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name varchar,
  position varchar,
  duration_months int,
  key_achievements text,
  technologies_used text,
  is_relevant boolean,
  transferability_to_role transferability_type,
  experience_gravity experience_gravity_type,
  evaluation_criteria_score_id int
);

CREATE TABLE packages (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  description text,
  package_target package_target_type NOT NULL,
  package_type package_type,
  original_price decimal(15,2) NOT NULL DEFAULT 0,
  sale_price decimal(15,2) NOT NULL DEFAULT 0,
  currency varchar(3) NOT NULL DEFAULT 'VND',
  billing_cycle billing_cycle_type NOT NULL,
  credit_quota int DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE features (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  description text,
  feature_key varchar(100) UNIQUE NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE credit_wallets (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int,
  candidate_id int,
  balance int
);

CREATE TABLE package_features (
  package_id int NOT NULL,
  feature_id int NOT NULL,
  max_quota int DEFAULT 0,
  PRIMARY KEY (package_id, feature_id)
);

CREATE TABLE subscriptions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int,
  package_id int NOT NULL,
  price decimal(15,2) NOT NULL DEFAULT 0,
  status subscription_status NOT NULL DEFAULT 'pending_payment',
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  purchased_at TIMESTAMP DEFAULT now(),
  renewed_at TIMESTAMP
);

CREATE TABLE credit_transactions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credit_wallet_id int NOT NULL,
  credit_type credit_type NOT NULL,
  amount int NOT NULL,
  reference_type reference_type,
  description text,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE payment_histories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id int NOT NULL,
  amount decimal(15,2) NOT NULL,
  currency varchar(3) NOT NULL DEFAULT 'VND',
  payment_method payment_method_type NOT NULL,
  payment_status payment_status_type NOT NULL DEFAULT 'pending',
  transaction_code varchar(255),
  paid_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE notifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  notification_type notification_type NOT NULL,
  title varchar(255) NOT NULL,
  message text NOT NULL,
  related_entity_type varchar(50),
  related_entity_id int,
  is_read boolean NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE notification_settings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  notification_type notification_type NOT NULL,
  email_enabled boolean NOT NULL DEFAULT true,
  in_app_enabled boolean NOT NULL DEFAULT true
);

CREATE TABLE faqs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category varchar(100) NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  is_published boolean NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE export_records (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exported_by int NOT NULL,
  job_id int NOT NULL,
  export_type export_type NOT NULL,
  candidate_count int NOT NULL DEFAULT 0,
  file_url varchar(500),
  created_at TIMESTAMP DEFAULT now()
);

-- ==============================================
-- INDEXES
-- ==============================================

CREATE UNIQUE INDEX ON notification_settings (user_id, notification_type);

-- ==============================================
-- FOREIGN KEYS
-- ==============================================

ALTER TABLE users_roles ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE users_roles ADD FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE;

ALTER TABLE candidates ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE recruiters ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE recruiters ADD FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;

ALTER TABLE user_tokens ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE TABLE jobs_job_domains (
  job_id int,
  job_domain_id int,
  PRIMARY KEY (job_id, job_domain_id)
);

ALTER TABLE jobs_job_domains ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE jobs_job_domains ADD FOREIGN KEY (job_domain_id) REFERENCES job_domains (id);

ALTER TABLE job_benefits ADD FOREIGN KEY (id) REFERENCES jobs (id);

ALTER TABLE job_expertises ADD FOREIGN KEY (id) REFERENCES job_expertise_groups (id);

ALTER TABLE job_answers ADD FOREIGN KEY (job_question_id) REFERENCES job_questions (id);

ALTER TABLE job_marks ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_marks ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE applications ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE applications ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE job_answers ADD FOREIGN KEY (application_id) REFERENCES applications (id);

ALTER TABLE job_questions ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE scoring_criterias ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE jobs ADD FOREIGN KEY (root_id) REFERENCES jobs (id);

ALTER TABLE scoring_criterias ADD FOREIGN KEY (criteria_id) REFERENCES criterias (id);

ALTER TABLE job_skills ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE job_locations ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE resume_skills ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE resume_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_educations ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE skills ADD FOREIGN KEY (category_id) REFERENCES skill_categories (id);

ALTER TABLE resume_projects ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE project_skills ADD FOREIGN KEY (project_id) REFERENCES resume_projects (id);

ALTER TABLE project_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_experiences ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE resume_experience_details ADD FOREIGN KEY (experience_id) REFERENCES resume_experiences (id);

ALTER TABLE experience_skills ADD FOREIGN KEY (detail_id) REFERENCES resume_experience_details (id);

ALTER TABLE experience_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_certifications ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE evaluation_weaknesses ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE resume_evaluations ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE evaluation_criteria_scores ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE package_features ADD FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE CASCADE;

ALTER TABLE package_features ADD FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE;

ALTER TABLE subscriptions ADD FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;

ALTER TABLE payment_histories ADD FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE;

ALTER TABLE subscriptions ADD FOREIGN KEY (package_id) REFERENCES packages (id);

ALTER TABLE applications ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE notifications ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notification_settings ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE export_records ADD FOREIGN KEY (exported_by) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE export_records ADD FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE;

ALTER TABLE company_follows ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE company_blocked_candidates ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE company_images ADD FOREIGN KEY (id) REFERENCES companies (id);

ALTER TABLE company_locations ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE jobs ADD FOREIGN KEY (id) REFERENCES job_expertises (id);

ALTER TABLE jobs ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE credit_transactions ADD FOREIGN KEY (credit_wallet_id) REFERENCES credit_wallets (id);

ALTER TABLE credit_wallets ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE credit_wallets ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE evaluation_hard_skills ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_soft_skills ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_experience_details ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_gaps ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE evaluation_criteria_scores ADD FOREIGN KEY (scoring_criteria_id) REFERENCES scoring_criterias (id);
