-- ==============================================
-- ENUM TYPES FOR POSTGRESQL
-- ==============================================

-- Users
CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION');
CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY');
CREATE TYPE token_type AS ENUM ('ACCESS', 'REFRESH', 'RESET_PASSWORD', 'EMAIL_VERIFICATION');

-- Jobs
CREATE TYPE job_status AS ENUM ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'SUSPENDED', 'CLOSED');
CREATE TYPE job_level_type AS ENUM ('INTERN', 'JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', 'MANAGER');
CREATE TYPE working_model_type AS ENUM ('REMOTE', 'ONSITE', 'HYBRID');

-- Applications
CREATE TYPE application_status AS ENUM ('APPLIED', 'VIEWED', 'SHORTLISTED', 'AUTO_REJECTED', 'NOT_SUITABLE');

-- Candidates
CREATE TYPE job_search_status AS ENUM ('ACTIVELY_LOOKING', 'OPEN_TO_OFFERS', 'NOT_LOOKING');

-- Criteria
CREATE TYPE criteria_type AS ENUM ('HARD_SKILLS', 'SOFT_SKILLS', 'EXPERIENCE', 'EDUCATION', 'JOB_TITLE', 'JOB_LEVEL');

-- Company
CREATE TYPE company_status AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED');

-- Resume
CREATE TYPE resume_status AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
CREATE TYPE resume_language AS ENUM ('VI', 'EN');
CREATE TYPE degree_type AS ENUM ('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE', 'CERTIFICATE');
CREATE TYPE project_type AS ENUM ('PERSONAL', 'ACADEMIC', 'PROFESSIONAL', 'OPEN_SOURCE', 'FREELANCE');

-- Evaluation
CREATE TYPE gap_type AS ENUM ('HARD_SKILL', 'SOFT_SKILL', 'EXPERIENCE', 'EDUCATION', 'CERTIFICATION');
CREATE TYPE impact_type AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');
CREATE TYPE match_level_type AS ENUM ('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'NOT_MATCHED');
CREATE TYPE evaluation_status_type AS ENUM ('WAITING', 'PARTIAL', 'FINISH', 'FAIL');
CREATE TYPE skill_category_type AS ENUM ('PROGRAMMING_LANGUAGE', 'FRAMEWORK', 'TOOL', 'DATABASE', 'OTHER');
CREATE TYPE skill_level_type AS ENUM ('JUNIOR', 'MID', 'SENIOR', 'EXPERT');
CREATE TYPE relevance_type AS ENUM ('HIGH', 'MEDIUM', 'LOW');
CREATE TYPE transferability_type AS ENUM ('HIGH', 'MEDIUM', 'LOW');
CREATE TYPE experience_gravity_type AS ENUM ('HIGH', 'MEDIUM', 'LOW');

-- Packages
CREATE TYPE package_target_type AS ENUM ('CANDIDATE', 'COMPANY');
CREATE TYPE package_type AS ENUM ('CREDIT', 'FEATURE');
CREATE TYPE billing_cycle_type AS ENUM ('MONTHLY', 'YEARLY', 'ONE_TIME');
CREATE TYPE subscription_status AS ENUM ('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING_PAYMENT');
CREATE TYPE credit_type AS ENUM ('EARNED', 'CONSUMED', 'EXPIRED', 'BONUS');
CREATE TYPE reference_type AS ENUM ('AI_SUGGESTION', 'MATCHING_SCORE', 'CV_SCORE', 'TALENT_UNLOCK', 'CYCLE_RESET', 'TRIAL');
CREATE TYPE payment_method_type AS ENUM ('CREDIT_CARD', 'VNPAY', 'SEPAY', 'MOMO', 'BANK_TRANSFER');
CREATE TYPE payment_status_type AS ENUM ('PENDING', 'SUCCESS', 'FAILED');

-- Notifications
CREATE TYPE notification_type AS ENUM ('APPLICATION_STATUS', 'REJECTION', 'COMPANY_REGISTRATION', 'FLAGGED_JOB', 'PAYMENT_FAILURE', 'AI_DOWNTIME', 'SYSTEM');

-- Export
CREATE TYPE export_type AS ENUM ('XLSX', 'CSV');

-- ==============================================
-- TABLE DEFINITIONS
-- ==============================================

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  status user_status,
  full_name varchar(255),
  avatar varchar(500),
  last_login_at TIMESTAMP,
  date_of_birth TIMESTAMP,
  gender gender_type,
  role_id int
);

CREATE TABLE user_tokens (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  token varchar(500) UNIQUE NOT NULL,
  token_type token_type NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  revoked boolean DEFAULT false,
  revoked_at TIMESTAMP,
  ip_address varchar(45),
  user_agent varchar(500)
);

CREATE TABLE roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(10)
);

CREATE TABLE candidates (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int UNIQUE NOT NULL,
  job_title varchar(255),
  linkedin_url varchar(500),
  github_url varchar(500),
  website_url varchar(500),
  expected_salary_min decimal(15,2),
  expected_salary_max decimal(15,2),
  job_search_status job_search_status DEFAULT 'OPEN_TO_OFFERS',
  availability_date date,
  is_profile_public boolean DEFAULT true,
  profile_completeness int DEFAULT 0
);

CREATE TABLE recruiters (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int UNIQUE NOT NULL,
  company_id int NOT NULL,
  is_verified boolean DEFAULT false,
  is_root_candidate boolean DEFAULT false,
  verified_at TIMESTAMP
);

CREATE TABLE jobs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  about text,
  responsibilities text,
  requirement text,
  is_violated boolean,
  upload_time TIMESTAMP,
  exp_date TIMESTAMP,
  salary_start decimal(15,2),
  salary_end decimal(15,2),
  currency varchar(3) DEFAULT 'VND',
  experience_time int,
  enable_ai_scoring boolean,
  status job_status,
  job_level job_level_type,
  working_model working_model_type,
  quantity int,
  auto_reject_threshold DOUBLE PRECISION,
  root_id int,
  company_id int,
  expertise_id int
);

CREATE TABLE applications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status application_status,
  attempt int,
  full_name varchar,
  phone varchar,
  email varchar,
  applied_at TIMESTAMP,
  candidate_id int,
  resume_id int,
  job_id int
);

CREATE TABLE scoring_criterias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  context text,
  weight DOUBLE PRECISION,
  job_id int,
  criteria_id int
);

CREATE TABLE criterias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  criteria_type criteria_type,
  default_weight DOUBLE PRECISION
);

CREATE TABLE job_marks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int,
  job_id int
);

CREATE TABLE job_expertise_groups (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE benefits (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE job_benefits (
  job_id int,
  benefit_id int,
  PRIMARY KEY (job_id, benefit_id)
);

CREATE TABLE job_locations (
  company_location_id int,
  job_id int,
  PRIMARY KEY (company_location_id, job_id)
);

CREATE TABLE job_questions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  is_required bool,
  description text,
  job_id int
);

CREATE TABLE job_answers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  answer text,
  application_id int,
  job_question_id int
);

CREATE TABLE domains (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text
);

CREATE TABLE job_domains (
  job_id int,
  domain_id int,
  PRIMARY KEY (job_id, domain_id)
);

CREATE TABLE job_expertises (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description text,
  expertise_group_id int
);

CREATE TABLE job_skills (
  skill_id int,
  job_id int
);

CREATE TABLE company_images (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url varchar,
  description varchar
);

CREATE TABLE companies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  country varchar,
  company_industry varchar,
  size varchar,
  description text,
  link varchar,
  follower_number int,
  status company_status,
  company_type varchar,
  logo varchar,
  tax_identification_number varchar,
  email varchar,
  phone varchar,
  sign_commitment boolean,
  erc varchar
);

CREATE TABLE company_blocked_candidates (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id int,
  block_date TIMESTAMP,
  reason varchar
);

CREATE TABLE company_follows (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int,
  candidate_id int
);

CREATE TABLE company_locations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int NOT NULL,
  name varchar,
  address varchar,
  district varchar,
  city varchar,
  country varchar,
  description varchar,
  longitude decimal(10, 7),
  latitude decimal(10, 7),
  google_map_link varchar(500)
);

CREATE TABLE resumes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name varchar,
  original_file varchar,
  raw_text text,
  address_in_resume varchar,
  phone_in_resume varchar,
  email_in_resume varchar,
  github_link varchar,
  linkedin_link varchar,
  portfolio_link varchar,
  full_name varchar,
  avatar varchar,
  resume_url varchar(500),
  is_original boolean DEFAULT true,
  status resume_status,
  language resume_language,
  candidate_id int
);

CREATE TABLE skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar,
  category_id int
);

CREATE TABLE skill_categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE resume_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_skill_section TEXT,
  skill_id int,
  resume_id int
);

CREATE TABLE resume_educations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution varchar,
  degree degree_type,
  major_field varchar,
  gpa DOUBLE PRECISION,
  start_date date,
  end_date date,
  is_current bool,
  resume_id int
);

CREATE TABLE resume_experiences (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company varchar,
  start_date date,
  end_date date,
  is_current bool,
  resume_id int
);

CREATE TABLE resume_projects (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar,
  team_size int,
  position varchar,
  description text,
  project_type project_type,
  start_date date,
  end_date date,
  is_current bool,
  project_url varchar,
  resume_id int
);

CREATE TABLE resume_certifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  issuer varchar,
  credential_url varchar,
  image varchar,
  description text,
  resume_id int
);

CREATE TABLE resume_experience_details (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  title varchar,
  position varchar,
  start_date date,
  end_date date,
  is_current bool,
  experience_id int
);

CREATE TABLE experience_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  detail_id int,
  skill_id int
);

CREATE TABLE project_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  project_id int,
  skill_id int
);

CREATE TABLE evaluation_gaps (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gap_type gap_type,
  item_name varchar,
  description text,
  impact impact_type,
  impact_score float,
  suggestion text,
  evaluation_id int
);

CREATE TABLE evaluation_weaknesses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weakness_text text,
  suggestion text,
  start_index int,
  end_index int,
  context varchar,
  criterion_type criteria_type,
  severity smallint,
  evaluation_id int
);

CREATE TABLE resume_evaluations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_overall_score float,
  recruiter_overall_score float,
  match_level match_level_type,
  summary text,
  strengths text,
  weakness text,
  is_true_level bool,
  has_related_experience bool,
  is_specific_jd bool,
  evaluation_status evaluation_status_type,
  processing_time_second float,
  ai_model_version varchar,
  resume_id int,
  job_id int
);

CREATE TABLE evaluation_criteria_scores (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scoring_criteria_id int,
  max_score float DEFAULT 100,
  ai_score float,
  manual_score float,
  weighted_score float,
  ai_explanation text,
  manual_explanation text,
  evaluation_id int
);

CREATE TABLE evaluation_hard_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name varchar,
  evidence text,
  skill_category skill_category_type,
  required_level skill_level_type,
  candidate_level skill_level_type,
  match_score float,
  years_of_experience float,
  is_critical bool,
  is_matched bool,
  is_missing bool,
  is_extra bool,
  relevance relevance_type,
  evaluation_criteria_score_id int
);

CREATE TABLE evaluation_soft_skills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_name varchar,
  evidence text,
  is_required boolean,
  is_found boolean,
  evaluation_criteria_score_id int
);

CREATE TABLE evaluation_experience_details (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name varchar,
  position varchar,
  duration_months int,
  key_achievements text,
  technologies_used text,
  is_relevant boolean,
  transferability_to_role transferability_type,
  experience_gravity experience_gravity_type,
  evaluation_criteria_score_id int
);

CREATE TABLE packages (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  description text,
  package_target package_target_type NOT NULL,
  package_type package_type,
  original_price decimal(15,2) NOT NULL DEFAULT 0,
  sale_price decimal(15,2) NOT NULL DEFAULT 0,
  currency varchar(3) NOT NULL DEFAULT 'VND',
  billing_cycle billing_cycle_type NOT NULL,
  credit_quota int DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE features (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  description text,
  feature_key varchar(100) UNIQUE NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE credit_wallets (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int,
  candidate_id int,
  balance int
);

CREATE TABLE package_features (
  package_id int NOT NULL,
  feature_id int NOT NULL,
  max_quota int DEFAULT 0,
  PRIMARY KEY (package_id, feature_id)
);

CREATE TABLE subscriptions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id int,
  package_id int NOT NULL,
  price decimal(15,2) NOT NULL DEFAULT 0,
  status subscription_status NOT NULL DEFAULT 'PENDING_PAYMENT',
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  purchased_at TIMESTAMP DEFAULT now(),
  renewed_at TIMESTAMP
);

CREATE TABLE credit_transactions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credit_wallet_id int NOT NULL,
  credit_type credit_type NOT NULL,
  amount int NOT NULL,
  reference_type reference_type,
  description text,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE payment_histories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id int NOT NULL,
  amount decimal(15,2) NOT NULL,
  currency varchar(3) NOT NULL DEFAULT 'VND',
  payment_method payment_method_type NOT NULL,
  payment_status payment_status_type NOT NULL DEFAULT 'PENDING',
  transaction_code varchar(255),
  paid_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE notifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  notification_type notification_type NOT NULL,
  title varchar(255) NOT NULL,
  message text NOT NULL,
  related_entity_type varchar(50),
  related_entity_id int,
  is_read boolean NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE notification_settings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  notification_type notification_type NOT NULL,
  email_enabled boolean NOT NULL DEFAULT true,
  in_app_enabled boolean NOT NULL DEFAULT true
);

CREATE TABLE faqs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category varchar(100) NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  is_published boolean NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE export_records (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exported_by int NOT NULL,
  job_id int NOT NULL,
  export_type export_type NOT NULL,
  candidate_count int NOT NULL DEFAULT 0,
  file_url varchar(500),
  created_at TIMESTAMP DEFAULT now()
);

-- ==============================================
-- INDEXES
-- ==============================================

CREATE UNIQUE INDEX ON notification_settings (user_id, notification_type);

-- ==============================================
-- FOREIGN KEYS
-- ==============================================

ALTER TABLE users ADD FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE candidates ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE recruiters ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE recruiters ADD FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;

ALTER TABLE user_tokens ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE job_domains ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_domains ADD FOREIGN KEY (domain_id) REFERENCES domains (id);

ALTER TABLE job_benefits ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_benefits ADD FOREIGN KEY (benefit_id) REFERENCES benefits (id);

ALTER TABLE job_expertises ADD FOREIGN KEY (expertise_group_id) REFERENCES job_expertise_groups (id);

ALTER TABLE job_answers ADD FOREIGN KEY (job_question_id) REFERENCES job_questions (id);

ALTER TABLE job_marks ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_marks ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE applications ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE applications ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE job_answers ADD FOREIGN KEY (application_id) REFERENCES applications (id);

ALTER TABLE job_questions ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE scoring_criterias ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE jobs ADD FOREIGN KEY (root_id) REFERENCES jobs (id);

ALTER TABLE scoring_criterias ADD FOREIGN KEY (criteria_id) REFERENCES criterias (id);

ALTER TABLE job_skills ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE job_locations ADD FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE job_locations ADD FOREIGN KEY (company_location_id) REFERENCES company_locations (id);

ALTER TABLE resume_skills ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE resume_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_educations ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE skills ADD FOREIGN KEY (category_id) REFERENCES skill_categories (id);

ALTER TABLE resume_projects ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE project_skills ADD FOREIGN KEY (project_id) REFERENCES resume_projects (id);

ALTER TABLE project_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_experiences ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE resume_experience_details ADD FOREIGN KEY (experience_id) REFERENCES resume_experiences (id);

ALTER TABLE experience_skills ADD FOREIGN KEY (detail_id) REFERENCES resume_experience_details (id);

ALTER TABLE experience_skills ADD FOREIGN KEY (skill_id) REFERENCES skills (id);

ALTER TABLE resume_certifications ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE evaluation_weaknesses ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE resume_evaluations ADD FOREIGN KEY (resume_id) REFERENCES resumes (id);

ALTER TABLE evaluation_criteria_scores ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE package_features ADD FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE CASCADE;

ALTER TABLE package_features ADD FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE;

ALTER TABLE subscriptions ADD FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;

ALTER TABLE payment_histories ADD FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE;

ALTER TABLE subscriptions ADD FOREIGN KEY (package_id) REFERENCES packages (id);

ALTER TABLE applications ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE notifications ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notification_settings ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE export_records ADD FOREIGN KEY (exported_by) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE export_records ADD FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE;

ALTER TABLE company_follows ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE company_blocked_candidates ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE company_images ADD FOREIGN KEY (id) REFERENCES companies (id);

ALTER TABLE company_locations ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE jobs ADD FOREIGN KEY (expertise_id) REFERENCES job_expertises (id);

ALTER TABLE jobs ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE credit_transactions ADD FOREIGN KEY (credit_wallet_id) REFERENCES credit_wallets (id);

ALTER TABLE credit_wallets ADD FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE credit_wallets ADD FOREIGN KEY (candidate_id) REFERENCES candidates (id);

ALTER TABLE evaluation_hard_skills ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_soft_skills ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_experience_details ADD FOREIGN KEY (evaluation_criteria_score_id) REFERENCES evaluation_criteria_scores (id);

ALTER TABLE evaluation_gaps ADD FOREIGN KEY (evaluation_id) REFERENCES resume_evaluations (id);

ALTER TABLE evaluation_criteria_scores ADD FOREIGN KEY (scoring_criteria_id) REFERENCES scoring_criterias (id);

-- ==============================================
-- INITIAL DATA
-- ==============================================

INSERT INTO roles (name) VALUES ('CANDIDATE'), ('ADMIN'), ('RECRUITER');

-- Init Company
INSERT INTO companies (name, country, company_industry, size, description, status, email, phone) 
VALUES ('Tech Innovations', 'Vietnam', 'Information Technology', '50-100', 'Leading tech solution provider', 'ACTIVE', 'contact@techinnovations.com', '0123456789');

-- Init Company Location
INSERT INTO company_locations (company_id, name, address, district, city, country, description)
VALUES ((SELECT id FROM companies WHERE name = 'Tech Innovations'), 'Headquarters', '123 Tech Park', 'District 1', 'Ho Chi Minh City', 'Vietnam', 'Main Office');

-- Init User (Recruiter)
INSERT INTO users (email, password_hash, status, full_name, role_id) 
VALUES ('recruiter@techinnovations.com', '$2a$10$NotRealHashJustExample', 'ACTIVE', 'John Recruiter', (SELECT id FROM roles WHERE name = 'RECRUITER'));

-- Link User to Company (Recruiter)
INSERT INTO recruiters (user_id, company_id, is_verified) 
VALUES ((SELECT id FROM users WHERE email = 'recruiter@techinnovations.com'), (SELECT id FROM companies WHERE name = 'Tech Innovations'), true);

-- Init Expertise
INSERT INTO job_expertise_groups (name, description) VALUES ('Software Development', 'All software related jobs');
INSERT INTO job_expertises (name, description, expertise_group_id) 
VALUES ('Backend Developer', 'Server side development', (SELECT id FROM job_expertise_groups WHERE name = 'Software Development'));

-- Init Skills
INSERT INTO skill_categories (name) VALUES ('Programming Language'), ('Framework');
INSERT INTO skills (name, category_id) VALUES ('Java', (SELECT id FROM skill_categories WHERE name = 'Programming Language'));
INSERT INTO skills (name, category_id) VALUES ('Spring Boot', (SELECT id FROM skill_categories WHERE name = 'Framework'));
INSERT INTO skills (name, category_id) VALUES ('PostgreSQL', (SELECT id FROM skill_categories WHERE name = 'Programming Language'));

-- Init Benefits
INSERT INTO benefits (name, description) VALUES ('Health Insurance', 'Full coverage'), ('Flexible Hours', 'Work anytime');

-- Init Job 1
INSERT INTO jobs (name, about, responsibilities, requirement, salary_start, salary_end, currency, status, job_level, working_model, quantity, company_id, expertise_id) 
VALUES (
    'Senior Backend Engineer', 
    'Join our core team enabling high scale.', 
    'Design and implement microservices.', 
    '5+ years in Java, Spring Boot.', 
    30000000, 60000000, 'VND', 
    'APPROVED', 
    'SENIOR', 
    'HYBRID', 
    2, 
    (SELECT id FROM companies WHERE name = 'Tech Innovations'), 
    (SELECT id FROM job_expertises WHERE name = 'Backend Developer')
);

-- Init Job 2
INSERT INTO jobs (name, about, responsibilities, requirement, salary_start, salary_end, currency, status, job_level, working_model, quantity, company_id, expertise_id) 
VALUES (
    'Junior Java Developer', 
    'Great opportunity for learning.', 
    'Maintain existing codebase.', 
    '1+ years in Java.', 
    15000000, 25000000, 'VND', 
    'APPROVED', 
    'JUNIOR', 
    'ONSITE', 
    5, 
    (SELECT id FROM companies WHERE name = 'Tech Innovations'), 
    (SELECT id FROM job_expertises WHERE name = 'Backend Developer')
);

-- Link Job 1 Relations
INSERT INTO job_skills (job_id, skill_id) VALUES 
((SELECT id FROM jobs WHERE name = 'Senior Backend Engineer'), (SELECT id FROM skills WHERE name = 'Java')),
((SELECT id FROM jobs WHERE name = 'Senior Backend Engineer'), (SELECT id FROM skills WHERE name = 'Spring Boot'));

INSERT INTO job_benefits (job_id, benefit_id) VALUES 
((SELECT id FROM jobs WHERE name = 'Senior Backend Engineer'), (SELECT id FROM benefits WHERE name = 'Health Insurance'));

INSERT INTO job_locations (job_id, company_location_id) VALUES 
((SELECT id FROM jobs WHERE name = 'Senior Backend Engineer'), (SELECT id FROM company_locations WHERE name = 'Headquarters'));

-- Link Job 2 Relations
INSERT INTO job_skills (job_id, skill_id) VALUES 
((SELECT id FROM jobs WHERE name = 'Junior Java Developer'), (SELECT id FROM skills WHERE name = 'Java'));

INSERT INTO job_benefits (job_id, benefit_id) VALUES 
((SELECT id FROM jobs WHERE name = 'Junior Java Developer'), (SELECT id FROM benefits WHERE name = 'Flexible Hours'));

INSERT INTO job_locations (job_id, company_location_id) VALUES 
((SELECT id FROM jobs WHERE name = 'Junior Java Developer'), (SELECT id FROM company_locations WHERE name = 'Headquarters'));


