BEGIN;

DO $$
BEGIN
    CREATE TYPE employment_type AS ENUM (
        'FULL_TIME',
        'PART_TIME',
        'SELF_EMPLOYED',
        'FREELANCE',
        'CONTRACT',
        'INTERNSHIP',
        'APPRENTICESHIP',
        'SEASONAL'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE resume_educations
    ADD COLUMN IF NOT EXISTS order_index int;

ALTER TABLE resume_experiences
    ADD COLUMN IF NOT EXISTS working_model working_model_type,
    ADD COLUMN IF NOT EXISTS employment_type employment_type,
    ADD COLUMN IF NOT EXISTS order_index int;

ALTER TABLE resume_projects
    ADD COLUMN IF NOT EXISTS order_index int;

ALTER TABLE resume_experience_details
    ADD COLUMN IF NOT EXISTS order_index int;

ALTER TABLE resume_experience_details
    DROP COLUMN IF EXISTS position;

CREATE TABLE IF NOT EXISTS resume_skill_groups (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    order_index int,
    resume_id int
);

ALTER TABLE resume_skill_groups
    ADD COLUMN IF NOT EXISTS name varchar,
    ADD COLUMN IF NOT EXISTS order_index int,
    ADD COLUMN IF NOT EXISTS resume_id int;

ALTER TABLE resume_skills
    ADD COLUMN IF NOT EXISTS skill_group_id int;

WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY resume_id ORDER BY id) AS rn
    FROM resume_educations
)
UPDATE resume_educations e
SET order_index = ranked.rn
FROM ranked
WHERE e.id = ranked.id
  AND e.order_index IS NULL;

WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY resume_id ORDER BY id) AS rn
    FROM resume_experiences
)
UPDATE resume_experiences e
SET order_index = ranked.rn
FROM ranked
WHERE e.id = ranked.id
  AND e.order_index IS NULL;

WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY resume_id ORDER BY id) AS rn
    FROM resume_projects
)
UPDATE resume_projects p
SET order_index = ranked.rn
FROM ranked
WHERE p.id = ranked.id
  AND p.order_index IS NULL;

WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY experience_id ORDER BY id) AS rn
    FROM resume_experience_details
)
UPDATE resume_experience_details d
SET order_index = ranked.rn
FROM ranked
WHERE d.id = ranked.id
  AND d.order_index IS NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'resume_skills'
          AND column_name = 'resume_id'
    ) THEN
        INSERT INTO resume_skill_groups (name, order_index, resume_id)
        SELECT grouped.group_name,
               ROW_NUMBER() OVER (PARTITION BY grouped.resume_id ORDER BY grouped.group_name),
               grouped.resume_id
        FROM (
            SELECT DISTINCT
                   rs.resume_id,
                   COALESCE(NULLIF(TRIM(sc.name), ''), 'Ungrouped') AS group_name
            FROM resume_skills rs
            LEFT JOIN skills s ON s.id = rs.skill_id
            LEFT JOIN skill_categories sc ON sc.id = s.category_id
            WHERE rs.resume_id IS NOT NULL
        ) grouped
        WHERE NOT EXISTS (
            SELECT 1
            FROM resume_skill_groups existing
            WHERE existing.resume_id = grouped.resume_id
              AND LOWER(REGEXP_REPLACE(TRIM(existing.name), '\s+', ' ', 'g'))
                    = LOWER(REGEXP_REPLACE(TRIM(grouped.group_name), '\s+', ' ', 'g'))
        );

        INSERT INTO resume_skill_groups (name, order_index, resume_id)
        SELECT 'Ungrouped',
               next_index.next_order,
               resume_with_skills.resume_id
        FROM (
            SELECT DISTINCT rs.resume_id
            FROM resume_skills rs
            WHERE rs.resume_id IS NOT NULL
        ) resume_with_skills
        JOIN LATERAL (
            SELECT COALESCE(MAX(rsg.order_index), 0) + 1 AS next_order
            FROM resume_skill_groups rsg
            WHERE rsg.resume_id = resume_with_skills.resume_id
        ) next_index ON TRUE
        WHERE NOT EXISTS (
            SELECT 1
            FROM resume_skill_groups rsg
            WHERE rsg.resume_id = resume_with_skills.resume_id
              AND LOWER(REGEXP_REPLACE(TRIM(rsg.name), '\s+', ' ', 'g'))
                    = LOWER(REGEXP_REPLACE(TRIM('Ungrouped'), '\s+', ' ', 'g'))
        );

        UPDATE resume_skills rs
        SET skill_group_id = rsg.id
        FROM skills s
        LEFT JOIN skill_categories sc ON sc.id = s.category_id
        JOIN resume_skill_groups rsg ON TRUE
        WHERE rs.skill_group_id IS NULL
          AND s.id = rs.skill_id
          AND rsg.resume_id = rs.resume_id
          AND LOWER(REGEXP_REPLACE(TRIM(rsg.name), '\s+', ' ', 'g'))
                = LOWER(REGEXP_REPLACE(TRIM(COALESCE(NULLIF(sc.name, ''), 'Ungrouped')), '\s+', ' ', 'g'));

        UPDATE resume_skills rs
        SET skill_group_id = rsg.id
        FROM resume_skill_groups rsg
        WHERE rs.skill_group_id IS NULL
          AND rs.resume_id = rsg.resume_id
          AND LOWER(REGEXP_REPLACE(TRIM(rsg.name), '\s+', ' ', 'g'))
                = LOWER(REGEXP_REPLACE(TRIM('Ungrouped'), '\s+', ' ', 'g'));
    END IF;
END $$;

WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY resume_id ORDER BY id) AS rn
    FROM resume_skill_groups
)
UPDATE resume_skill_groups rsg
SET order_index = ranked.rn
FROM ranked
WHERE rsg.id = ranked.id
  AND rsg.order_index IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM resume_educations WHERE order_index IS NULL) THEN
        ALTER TABLE resume_educations ALTER COLUMN order_index SET NOT NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM resume_experiences WHERE order_index IS NULL) THEN
        ALTER TABLE resume_experiences ALTER COLUMN order_index SET NOT NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM resume_projects WHERE order_index IS NULL) THEN
        ALTER TABLE resume_projects ALTER COLUMN order_index SET NOT NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM resume_experience_details WHERE order_index IS NULL) THEN
        ALTER TABLE resume_experience_details ALTER COLUMN order_index SET NOT NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM resume_skill_groups WHERE name IS NULL OR order_index IS NULL OR resume_id IS NULL) THEN
        ALTER TABLE resume_skill_groups ALTER COLUMN name SET NOT NULL;
        ALTER TABLE resume_skill_groups ALTER COLUMN order_index SET NOT NULL;
        ALTER TABLE resume_skill_groups ALTER COLUMN resume_id SET NOT NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM resume_skills WHERE skill_group_id IS NULL) THEN
        ALTER TABLE resume_skills ALTER COLUMN skill_group_id SET NOT NULL;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_resume_skill_groups_name_per_resume
ON resume_skill_groups (resume_id, (LOWER(REGEXP_REPLACE(TRIM(name), '\s+', ' ', 'g'))));

DO $$
DECLARE
    resume_skills_fk RECORD;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_resume_skill_groups_resume_id') THEN
        ALTER TABLE resume_skill_groups
            ADD CONSTRAINT fk_resume_skill_groups_resume_id
                FOREIGN KEY (resume_id) REFERENCES resumes (id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_resume_skills_skill_group_id') THEN
        ALTER TABLE resume_skills
            ADD CONSTRAINT fk_resume_skills_skill_group_id
                FOREIGN KEY (skill_group_id) REFERENCES resume_skill_groups (id);
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'resume_skills'
          AND column_name = 'resume_id'
    ) AND NOT EXISTS (SELECT 1 FROM resume_skills WHERE skill_group_id IS NULL) THEN
        FOR resume_skills_fk IN
            SELECT c.conname
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
            WHERE t.relname = 'resume_skills'
              AND c.contype = 'f'
              AND a.attname = 'resume_id'
        LOOP
            EXECUTE format('ALTER TABLE resume_skills DROP CONSTRAINT %I', resume_skills_fk.conname);
        END LOOP;

        ALTER TABLE resume_skills DROP COLUMN resume_id;
    END IF;
END $$;

COMMIT;
